apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boutique
nameSuffix: -dev
resources:
- ../../bases/boutique
- namespace.yaml
transformers:
- labels.yaml
replicas:
- count: 1
  name: frontend
images:
- name: gcr.io/google-samples/microservices-demo/frontend
  newTag: v0.2.3
- count: 1
  name: recommendationservice
images:
- name: gcr.io/google-samples/microservices-demo/recommendationservice
  newTag: v0.2.3
